sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: true

script:
  - ./gradlew build

  - docker build -t kaitoedter/movies-demo backend/build
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push kaitoedter/movies-demo

  - docker tag kaitoedter/movies-demo registry.heroku.com/hypermedia-movies-demo/web
  - docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com
  - docker push registry.heroku.com/hypermedia-movies-demo/web
  - ./heroku-container-release.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
